/*******************************************************************************************************************************************************
EXCLUSIVE ON themeforest.net
********************************************************************************************************************************************************
Template Name   : MHJ University
Author          : MoazzemHJesan
Author URL      : https://themeforest.net/user/moazzemhjesan
version         : 1.0
********************************************************************************************************************************************************
Copyright (c) 2023 - MoazzemHJesan
*******************************************************************************************************************************************************/
(function(){var t,i,e,s,n,r,o,a,u,$,c,m;e=100,t=[[253,83,64],[0,176,75],[16,64,36],[244,92,68],[90,255,160]],s=2*Math.PI,o=(n=document.getElementById("confetti")).getContext("2d"),window.w=0,window.h=0,c=function(){return window.w=n.width=window.innerWidth,window.h=n.height=window.innerHeight},window.addEventListener("resize",c,!1),window.onload=function(){return setTimeout(c,0)},$=function(t,i){return(i-t)*Math.random()+t},a=function(t,i,e,n){return o.beginPath(),o.arc(t,i,e,0,s,!1),o.fillStyle=n,o.fill()},m=.5,document.onmousemove=function(t){return m=t.pageX/w},window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(t){return window.setTimeout(t,1e3/60)},i=function(){function i(){this.style=t[~~$(0,5)],this.rgb="rgba("+this.style[0]+","+this.style[1]+","+this.style[2],this.r=~~$(2,6),this.r2=2*this.r,this.replace()}return i.prototype.replace=function(){return this.opacity=0,this.dop=.03*$(1,4),this.x=$(-this.r2,w-this.r2),this.y=$(-20,h-this.r2),this.xmax=w-this.r,this.ymax=h-this.r,this.vx=$(0,2)+8*m-5,this.vy=.1*this.r+$(-1,1)},i.prototype.draw=function(){var t;return this.x+=this.vx,this.y+=this.vy,this.opacity+=this.dop,this.opacity>1&&(this.opacity=1,this.dop*=-1),(this.opacity<0||this.y>this.ymax)&&this.replace(),0<(t=this.x)&&t<this.xmax||(this.x=(this.x+this.xmax)%this.xmax),a(~~this.x,~~this.y,this.r,this.rgb+","+this.opacity+")")},i}(),r=function(){var t,s,n;for(n=[],u=t=1,s=e;1<=s?t<=s:t>=s;u=1<=s?++t:--t)n.push(new i);return n}(),window.step=function(){var t,i,e,s;for(requestAnimationFrame(step),o.clearRect(0,0,w,h),s=[],i=0,e=r.length;i<e;i++)t=r[i],s.push(t.draw());return s},step()}).call(this);